issues:
  exclude-use-default: true
  max-same-issues: 0
  max-issues-per-linter: 0

linters:
  disable-all: true
  enable:
    - bodyclose
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused

linters-settings:
  misspell:
    locale: US
output:
  uniq-by-line: false

run:
  skip-dirs-use-default: false
  timeout: 5m
