on:
  pull_request:

name: Lint

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          only-new-issues: true
